[package]
name = "supercilex-tests"
version = "0.3.3"
authors = ["Alex Saveau <saveau.alexandre@gmail.com>"]
edition = "2021"
description = "Test utilities I use."
repository = "https://github.com/SUPERCILEX/supercilex-tests"
keywords = ["test-utils"]
categories = ["development-tools::testing"]
license = "Apache-2.0"

[dependencies]
clap_builder = { version = "4.3.9", default-features = false, features = ["std"] }
expect-test = "1.4.1"
public-api = "0.31.2"
rustdoc-json = "0.8.6"
